### ISSUE TITLE
Content moderator term list examples fails to run in full

### ISSUE THREAD

**Issue by davidefiocco** [Azure-Samples/cognitive-services-python-sdk-samples#54] opened 2019-05-07 20:48 UTC
### This issue is for a: 
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Try running 
`python samples/vision/content_moderator_term_list_samples.py `
in the repo after having cloned repo, installed requirements and exported environment variables `CONTENTMODERATOR_SUBSCRIPTION_KEY` and `CONTENTMODERATOR_LOCATION` as outlined in the README

### Any log messages given by the failure

Script starts running but crashes with

```
> Refreshing the search index for list 123
> Traceback (most recent call last):
>   File "samples/vision/content_moderator_term_list_samples.py", line 176, in <module>
>     execute_samples(globals(), SUBSCRIPTION_KEY_ENV_NAME)
>   File "/home/davide/Sandbox/cognitive-services-python-sdk-samples/samples/tools.py", line 39, in execute_samples
>     start_sample(func, subscription_key)
>   File "/home/davide/Sandbox/cognitive-services-python-sdk-samples/samples/tools.py", line 22, in start_sample
>     func(subscription_key)
>   File "samples/vision/content_moderator_term_list_samples.py", line 96, in terms_lists
>     refresh_index = client.list_management_term_lists.refresh_index_method(list_id=list_id, language="eng")
>   File "/home/davide/Sandbox/cognitive/lib/python3.7/site-packages/azure/cognitiveservices/vision/contentmoderator/operations/list_management_term_lists_operations.py", line 362, in refresh_index_method
>     raise models.APIErrorException(self._deserialize, response)
> azure.cognitiveservices.vision.contentmoderator.models._models_py3.APIErrorException: Operation returned an invalid status code 'Not Found'
```

### Expected/desired behavior
The example should run in full

### OS and Version?
Linux, several distros

### Versions
azure-cognitiveservices-vision-contentmoderator==1.0.0

### Additional info

The problem lies in https://github.com/Azure-Samples/cognitive-services-python-sdk-samples/blob/6532857e3b2097ce72fa66f39668822ec54f7254/samples/vision/content_moderator_term_list_samples.py#L96 most likely.

**Comment by wiazur** [comment] 2019-11-28 02:47
@davidefiocco sorry for the big delay of response. The sample has changed some since May. I ran the code and did not find any errors. I assume the bug was fixed. If you are still having problems with this sample, report a new issue. Closing for now, since could not reproduce.

**Closed by wiazur** 2019-11-28 02:47 UTC
